# Generated by Django 6.0.3 on 2026-09-02 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('data', models.DateField()),
                ('detalhamento_atividade', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=50)),
                ('prioridade', models.CharField(max_length=50)),
                ('pontuacao', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='AtividadeInterdisciplinar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criterios_de_avaliacao', models.CharField(max_length=255)),
                ('orientador', models.CharField(max_length=100)),
                ('atividade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atividade.atividade')),
            ],
        ),
    ]
