# Generated by Django 5.2.16 on 2026-08-20 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('disciplinas', '0002_alter_disciplina_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('data', models.DateField()),
                ('detalhamento_atividade', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=50)),
                ('prioridade', models.CharField(max_length=50)),
                ('pontuacao', models.FloatField()),
                ('disciplinas', models.ManyToManyField(related_name='atividades', to='disciplinas.disciplina')),
            ],
        ),
    ]
