# Generated by Django 6.0.3 on 2026-09-02 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('atividade', '0001_initial'),
        ('disciplinas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividadeinterdisciplinar',
            name='disciplina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='disciplinas.disciplina'),
        ),
        migrations.AddField(
            model_name='atividade',
            name='disciplinas',
            field=models.ManyToManyField(related_name='atividades', through='atividade.AtividadeInterdisciplinar', to='disciplinas.disciplina'),
        ),
    ]
