# Generated by Django 6.0.3 on 2026-10-03 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atividade', '0003_alter_atividade_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividade',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='atividadeinterdisciplinar',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
