# Generated by Django 5.2.16 on 2026-09-16 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atividade', '0003_alter_atividade_id_and_more'),
        ('estudante', '0001_initial'),
        ('notificacao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacao',
            name='atividade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to='atividade.atividade'),
        ),
        migrations.AlterField(
            model_name='notificacao',
            name='estudante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to='estudante.estudante'),
        ),
        migrations.AlterField(
            model_name='notificacao',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
