# Generated by Django 6.0.3 on 2026-10-03 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudante', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudante',
            name='cpf',
            field=models.CharField(max_length=14),
        ),
    ]
