# Generated by Django 5.2.16 on 2026-08-20 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudante', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudante',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
