# Generated by Django 6.0.3 on 2026-08-27 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudante', '0002_alter_estudante_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudante',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
