# Generated by Django 6.0.3 on 2026-09-02 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estudante', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('detalhamento', models.CharField(max_length=255)),
                ('data', models.DateField()),
                ('estudante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metas', to='estudante.estudante')),
            ],
        ),
    ]
