# Generated by Django 6.0.3 on 2026-08-26 12:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meta',
            name='data',
            field=models.DateField(default=datetime.date(2026, 8, 26)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meta',
            name='titulo',
            field=models.CharField(default='Meta de teste', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='meta',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
