# Generated by Django 5.2.16 on 2026-08-31 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0002_meta_data_meta_titulo_alter_meta_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meta',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
