# Generated by Django 6.0.3 on 2026-10-03 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0002_alter_meta_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meta',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
