# Generated by Django 6.0.3 on 2026-08-20 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estudante', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NomeDisciplina', models.CharField(max_length=100)),
                ('estudante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudante.estudante')),
            ],
        ),
    ]
