# Generated by Django 6.0.3 on 2026-09-02 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('disciplinas', '0001_initial'),
        ('estudante', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplina',
            name='estudante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudante.estudante'),
        ),
    ]
