# Generated by Django 5.2.16 on 2026-09-16 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disciplinas', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplina',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
